version: '3.8'
services:
  backendspringboot:
    image: denniseckler/backendspringboot
    ports:
      - "8080:8080"
    working_dir: /app
    volumes:
      - ./BackendSpringBoot:/app
  frontendangularjs:
    image: denniseckler/frontendangularjs
    ports:
      - "4200:4200"
    volumes:
      - ./FrontendAngularJS:/app